services:
  clinica-db:
    container_name: clinica-db
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "clinica-db"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - pg-db-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "16543:80"
    depends_on:
      - clinica-db
    networks:
      - pg-db-network
    restart: always

networks:
  pg-db-network:
    driver: bridge
    
#http://localhost:16543/login?next=%2F